### ISSUE TITLE
Getting empty audio data?

### ISSUE THREAD

**Issue by BatmanAnino** [Lyx52/PiperSharp#2]
Heya,

First off thanks for sharing your work!

I tried using your PiperSharp package to make a little test application for Piper but i am running into some issues, managed to resolve the first ones but might've inevitably have created others by doing so? i'm currently stuck at a point of it successfully downloading piper & models, configuring piper & pretty much appearing to work, but InferAsync always returns a mere 46 bytes of data with no actual audio?

After copying your example code into some basic project (and poking at it a little to get some kind of basic structure i can reuse later for an actual application) i got 'access denied' errors which related to your process.Start() call inside of your InferAsync function, after some trail and error i've concluded that i needed to specifically point to the piper.exe file in the PiperProvider 'Location' variable, see below deviation from your example:
~~~
piperProvider = new PiperProvider(new PiperConfiguration() {
    Location = workingDirectory+"\\piper\\piper.exe", // Path to piper directory (in this case cwd/piper)
    Model = model // Loaded/downloaded VoiceModel
});
~~~
This resolved the error, but might be a wrong conclusion/"fix" on my part?

I've also tried loading the model after it was downloaded, restarting application/windows after downloading a model, making an even simpler project without using a class library, but none of that seems to matter, for as far as i can tell its happy with what little stuff i duct-taped on top and the issue is either somewhere in PiperSharp or caused by me still misunderstanding something about the example code?

If after reading this nothing jumps out at you as "bad", is there any chance you could have a look at the little test project i put together? its a basic class library 'wrapping' your nuget package (mostly for later use) and a basic console app using that class library, the whole thing is pretty much your example code poured into some functions. Im attaching a zip file below, any input based on the above is welcome and if you can have a quick look at the project that would be superb! 👍
[SpeechStuff.zip](https://github.com/Lyx52/PiperSharp/files/15236575/SpeechStuff.zip)

Thanks!
Best Regards, Anino

**Comment by Lyx52** [comment]
Hi! Thank you for your issue.
Regarding your first point, yes that seems to be an issue I overlooked I will add a default piper location to configuration, but regarding your second point about invalid audio clips, I cant seem to replicate it. Could you try deleting your piper directory and re-download it?

**Comment by BatmanAnino** [comment]
Heya,

Regarding the first point, the piper configuration value was already there but i guess the example code failed to take the /piper/piper.exe into account.

Regarding the second point, removing the piper directory has no effect other then it redownloading it and getting the same results.

Am i correct in understanding that if you run the little test project provided above does it create/play audio for you? because if so then i guess that means the code is fine but there's possibly some platform issue or something on my end?

**Comment by BatmanAnino** [comment]
Heya,

Tried your newest provided examples completely as-is without any changes & they have the exact same issue, seems to be working fine but produces no actual audio, just empty audio files.

Guess this means we can conclude its something on my end, any input (on what that something could be) is still very welcome, but also fine if you just wanna close the issue, im probably going to remove the nuget package and check out this repo (so i can try edit the code) and then just keep poking at it till it works or i give up 😂

This probably wasn't the best project idea for my wanna-be junior C# developer skills hehe.
If i do figure out what's causing it + come up with a solution ill let you know and make a pull request! 👍

Best regards,
Anino

**Comment by Lyx52** [comment]
Hi sorry for not answering, yes your example works for me. One thing you can try is launching piper from command line?
```
echo Welcome to the world of speech synthesis! | C:\path\to\piper\piper.exe --model C:\path\to\model\en_US-lessac-medium.onnx --output_file audio.wav
```

**Comment by Lyx52** [comment]
> Heya,
> 
> Tried your newest provided examples completely as-is without any changes & they have the exact same issue, seems to be working fine but produces no actual audio, just empty audio files.
> 
> Guess this means we can conclude its something on my end, any input (on what that something could be) is still very welcome, but also fine if you just wanna close the issue, im probably going to remove the nuget package and check out this repo (so i can try edit the code) and then just keep poking at it till it works or i give up 😂
> 
> This probably wasn't the best project idea for my wanna-be junior C# developer skills hehe. If i do figure out what's causing it + come up with a solution ill let you know and make a pull request! 👍
> 
> Best regards, Anino

Sure if you find anything to fix your issue create a pull request I will merge it.

**Comment by BatmanAnino** [comment]
Heya, 

Dont worry man, you're plenty responsive! 👍

Interesting idea i should've really thought off myself as well tbh, if i try use it from command line (the version of piper & the voice model it downloaded) it works just fine, creates a wav file that DOES contain voice audio..? 👍🤷‍♂️

I feel like there is something caused by AV or FW software or whatever that's not happy about the "process" logic, but idk if there's even a nice way around that (and not a fan of the whole "oh just disable it for developing" approach) ill go read up on stuff & get back to you if i find anything, lots of programs start other programs without any issues so idk why this has to be one 🤔

Thanks for the command line test idea, nice to see at least some part is working a-okay after all, good stuff! 👍

**Comment by BatmanAnino** [comment]
Heya,

Ehhh, messed around some more just trying random stuff, it has to be _something_ with my AV/FW (ESET Internet Security 17.1.11.0) or Win11 (Pro, 23H2, 22631.3527) or even Visual Studio (2022, 17.9.6) but its working now & i feel kind of dumb for not trying this before, but i'm also really _really **really**_ confused.

It doesn't work in the default project directory....? (ie: _"\Documents\Visual Studio 2022\Projects"_ that i use for literally everything because that's what its for right?!?!?) and any other directory (even also in Documents dir) is totally fine? 🤷‍♂️ I'm lost for words tbh.

In my testing i occasionally got it to error that "pipe is being closed" in your example project without any clear cause for that System.IO exception, this might be something you can look at if you want to investigate this weirdness further, but honestly what even, im 99% sure you can just ignore this whole thing and i need to reinstall windows or something like that...?!

Close at your digression & thank you for the help & your work/package! Happy to have it working & gonna try actually make something now hehe ^^ 👍

Best regards,
Anino
