### ISSUE TITLE
Suggestion to target .NET Standard 2.1 for wider compatibility

### ISSUE THREAD

**Issue by Nurgo** [Lyx52/PiperSharp#6]
Hello, and thank you for your great work, this project is really useful!

I wanted to suggest switching the target framework from .NET 6.0 to .NET Standard 2.1 to increase compatibility with a wider range of platforms. By targeting .NET Standard 2.1, the library could be used not only in modern .NET projects but also in applications that still rely on older frameworks like Xamarin, Unity and .NET Core 3.0, etc. It could also be used in projects that choose .Net Standard 2.1 for the same reason (which is my situation).

From my tests, the conversion process is quite simple. This small change could help expand the reach of the project while keeping things smooth for current users.

Thanks again for considering this, and for all the hard work you’ve put into this project!

**Comment by Lyx52** [comment]
Hi thank you for your suggestion, I will look into it when I have time.

**Comment by Lyx52** [comment]
Solved with [v1.0.5](https://github.com/Lyx52/PiperSharp/releases/tag/v1.0.5)
